# Generated by Django 3.0.8 on 2020-07-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='cookbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagescookbook', to='cookbook.Cookbook'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='havemessages', to='cookbook.Recipe'),
        ),
    ]
