# Generated by Django 3.0.8 on 2020-07-27 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20200726_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
        migrations.AddField(
            model_name='cookbook',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cookbook',
            name='recipes',
        ),
        migrations.AddField(
            model_name='cookbook',
            name='recipes',
            field=models.ManyToManyField(to='cookbook.Recipe', verbose_name='Recipes included'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
